In [1]:
import numpy as np

In [7]:
a = np.array([[1,4,2], [3,-1,0]])
b = np.array([[2,5],[2,0],[-1,3]])

In [10]:
# matrix multiplication
np.dot(a,b)

array([[ 8, 11],
       [ 4, 15]])

In [12]:
# scalar multiplication
b * 5

array([[10, 25],
       [10,  0],
       [-5, 15]])

In [16]:
a1 = np.array([[1,2], [3,4]])
a2 = np.array([[1,1], [2,2]])

In [17]:
a1 + a2

array([[2, 3],
       [5, 6]])